name: Build & deploy documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: docs-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_qadence_ubuntu:
    name: Test Qadence docs (ubuntu)
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout Qadence
      uses: actions/checkout@v4

    - name: Install JetBrains Mono font
      run: |
        sudo apt install -y wget unzip fontconfig
        wget https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip
        unzip JetBrainsMono-2.304.zip -d JetBrainsMono
        mkdir -p /usr/share/fonts/truetype/jetbrains
        cp JetBrainsMono/fonts/ttf/*.ttf /usr/share/fonts/truetype/jetbrains/
        fc-cache -f -v

    - name: Install graphviz
      run: sudo apt-get install -y graphviz

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Hatch
      run: |
        pip install hatch

    - name: Build docs
      if: ${{ !startsWith(github.ref, 'ref/tags/v') }}
      run: |
        hatch -v run docs:build

    - name: Deploy docs
      if: startsWith(github.ref, 'ref/tags/v')
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        mike deploy --push --update-aliases $VERSION latest
