name: Upload release to PyPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Qadence
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Build and publish package
        run: |
          hatch build
          hatch publish -u ${{ secrets.HATCH_PYPI_USER }} -a ${{ secrets.HATCH_PYPI_AUTH }}

      - name: Confirm deployment
        timeout-minutes: 5
        run: |
          VERSION=$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          until pip download qadence==$version
          do
            echo "Failed to download from PyPI, will wait for upload and retry."
            sleep 1
          done
