name: Upload release to PyPI

on:
  push:
    tag: "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Qadence
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Build and publish package
        shell: bash
        run: |
          hatch build
          hatch publish
