name: Test Qadence.

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop
  schedule:
    # 03:00 every Saturday morning
    - cron: '0 3 * * 6'
  workflow_dispatch: {}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_test_pytket_ubuntu:
    name: Build and test pytket (ubuntu)
    needs: check_changes
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Select Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Hatch
      run: |
        pip install hatch
    - name: Run tests
      run: |
        hatch -v run tests
