name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: examples-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_qadence_ubuntu:
    name: Examples (ubuntu)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install graphviz
      run: sudo apt-get install -y graphviz

    - name: Select Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Hatch
      run: |
        pip install hatch

    - name: Run example tests
      run: |
        hatch -v run test-examples
